//! Interactive setup wizard (`aurguard --setup`).
//!
//! Walks the user through interface language, the non-interactive install
//! policy, color preference, and any extra trusted domains, then writes a
//! `config.toml` to the user's config directory. Language is chosen first so
//! the remaining prompts are shown localized.

use crate::config::{Config, FailOn};
use crate::i18n::{t, Lang, K};
use anyhow::{Context, Result};
use std::io::{self, BufRead, Write};

/// Run the wizard. Returns the process exit code.
pub fn run() -> Result<i32> {
    let mut out = io::stderr();
    let stdin = io::stdin();
    let mut lines = stdin.lock().lines();

    // --- Language (neutral prompt, before localization) ---
    writeln!(out)?;
    writeln!(out, "  ┌─ aurguard setup ─ kurulum ─ configuration ─┐")?;
    writeln!(out)?;
    writeln!(out, "  Select language / Dil / Langue / Idioma / Dil:")?;
    for (i, l) in Lang::ALL.iter().enumerate() {
        writeln!(out, "    {}  {} ({})", i + 1, l.native_name(), l.code())?;
    }
    write!(out, "  [1-{}] (1): ", Lang::ALL.len())?;
    out.flush()?;
    let lang = match read_index(&mut lines, Lang::ALL.len()) {
        Some(i) => Lang::ALL[i],
        None => Lang::En,
    };

    // --- Install policy ---
    writeln!(out)?;
    writeln!(out, "  {}", t(lang, K::WizPolicyQ))?;
    writeln!(out, "    1  {}", t(lang, K::WizPolicyClean))?;
    writeln!(out, "    2  {}", t(lang, K::WizPolicyRisky))?;
    writeln!(out, "    3  {}", t(lang, K::WizPolicyCritical))?;
    write!(out, "  [1-3] (3): ")?;
    out.flush()?;
    let fail_on = match read_index(&mut lines, 3) {
        Some(0) => FailOn::Clean,
        Some(1) => FailOn::Risky,
        _ => FailOn::Critical,
    };

    // --- Color ---
    writeln!(out)?;
    write!(
        out,
        "  {} {}",
        t(lang, K::WizColorQ),
        t(lang, K::YesNoSuffix)
    )?;
    out.flush()?;
    let color = read_yes_no(&mut lines, true);

    // --- Extra trusted domains ---
    writeln!(out)?;
    write!(out, "  {}: ", t(lang, K::WizDomainsQ))?;
    out.flush()?;
    let domains_line = lines.next().transpose().ok().flatten().unwrap_or_default();
    let domains: Vec<String> = domains_line
        .split(',')
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .collect();

    // --- Write config ---
    let path = Config::default_path().context("could not determine config path")?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).ok();
    }
    let toml = render_config(lang, color, &domains, fail_on);
    std::fs::write(&path, toml).with_context(|| format!("failed to write {}", path.display()))?;

    writeln!(out)?;
    writeln!(
        out,
        "  ✓ {}",
        crate::i18n::fill(t(lang, K::WizSaved), Some(&path.display().to_string()))
    )?;
    Ok(0)
}

/// Render the `config.toml` contents.
fn render_config(lang: Lang, color: bool, domains: &[String], fail_on: FailOn) -> String {
    let domains_list = domains
        .iter()
        .map(|d| format!("\"{}\"", d.replace('"', "")))
        .collect::<Vec<_>>()
        .join(", ");
    let fail = match fail_on {
        FailOn::Clean => "clean",
        FailOn::Risky => "risky",
        FailOn::Critical => "critical",
    };
    format!(
        "# aurguard configuration (generated by `aurguard --setup`).\n\
         \n[ui]\n\
         lang = \"{}\"\n\
         color = {}\n\
         \n[trust]\n\
         extra_domains = [{}]\n\
         \n[rules]\n\
         ignore = []\n\
         \n[policy]\n\
         fail_on = \"{}\"\n",
        lang.code(),
        color,
        domains_list,
        fail
    )
}

/// Read a 1-based selection in `[1, max]`, returning the 0-based index, or
/// `None` on empty/invalid input.
fn read_index(lines: &mut impl Iterator<Item = io::Result<String>>, max: usize) -> Option<usize> {
    let line = lines.next()?.ok()?;
    match line.trim().parse::<usize>() {
        Ok(n) if n >= 1 && n <= max => Some(n - 1),
        _ => None,
    }
}

/// Read a yes/no answer, accepting localized affirmatives, with `default`.
fn read_yes_no(lines: &mut impl Iterator<Item = io::Result<String>>, default: bool) -> bool {
    let Some(Ok(line)) = lines.next() else {
        return default;
    };
    match line.trim().to_ascii_lowercase().as_str() {
        "" => default,
        "y" | "yes" | "e" | "evet" | "o" | "oui" | "s" | "si" | "sí" | "b" | "bəli" | "beli" => {
            true
        }
        _ => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_valid_toml() {
        let toml = render_config(Lang::Tr, true, &["git.acme.com".into()], FailOn::Risky);
        let cfg: Config = toml::from_str(&toml).unwrap();
        assert_eq!(cfg.ui.lang, Lang::Tr);
        assert_eq!(cfg.ui.color, Some(true));
        assert_eq!(cfg.trust.extra_domains, vec!["git.acme.com"]);
        assert_eq!(cfg.policy.fail_on, FailOn::Risky);
    }

    #[test]
    fn render_escapes_quotes_in_domains() {
        let toml = render_config(Lang::En, false, &["a\"b".into()], FailOn::Critical);
        // Must still parse (quote stripped).
        let cfg: Config = toml::from_str(&toml).unwrap();
        assert_eq!(cfg.trust.extra_domains, vec!["ab"]);
    }
}
